# swagger setting
springdoc:
  swagger-ui:
    path: /api-docs
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha # 정렬 기준
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

spring:
  redis:
    host: localhost
    port: 6379