# swagger settings
springdoc:
  swagger-ui:
    path: /api-docs
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha # 정렬 기준
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB


# AWS S3 settings
cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET_NAME}
      url: ${S3_URL}
      tripGenieProfileUrl: ${GENIE_PROFILE_URL}
    region:
      static: ${S3_REGION}
    stack:
      auto: false