spring:
  main:
    allow-bean-definition-overriding: true # for config error

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
        show_sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  redis:
    host: localhost
    port: 6379

logging:
  level:
    sql: info

# oauth settings
app:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    callback:
      url: ${GOOGLE_CALLBACK_URL}
    client:
      id: ${GOOGLE_CLIENT_ID}
      secret: ${GOOGLE_CLIENT_SECRET}
    auth:
      scope: profile,email
    token:
      url: https://oauth2.googleapis.com/token
    userinfo:
      url: https://www.googleapis.com/oauth2/v1/userinfo

  security:
    credential: ${SECRET_CREDENTIAL}

# swagger setting
springdoc:
  swagger-ui:
    path: /api-docs
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha # 정렬 기준
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

jwt:
  header: Authorization
  secret: c2FjYmFnYWppLXNwcmluZy1ib290LXNlY3VyaXR5LWp3dC1zZWNyZXQtdmFsdWUteWltLWd3YWsta2ltLWplb24tNC0xLWplb24tam9uZy1zdXJsLTEK
  live:
    atk: 1800000 # 60 * 30 * 1000
    rtk: 2592000000 # 60 * 60 * 24 * 30 * 1000