spring:
  config:
    activate:
      on-profile: local
---

spring:
  config:
    activate:
      on-profile: prod

  main:
    allow-bean-definition-overriding: true # for config error

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://simpletrip-db.cznmvedo4osi.ap-northeast-2.rds.amazonaws.com:3306/simpletrip
    username: admin
    password: simple123

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
        show_sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

logging:
  level:
    sql: info

# oauth settings
app:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    callback:
      url: http:/localhost:8080/oauth/google/callback
    client:
      id: 1059234526171-pp9kjq71447p213eprfv0so8qmohtaqj.apps.googleusercontent.com
      secret: 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
    auth:
      scope: profile,email
    token:
      url: https://oauth2.googleapis.com/token
    userinfo:
      url: https://www.googleapis.com/oauth2/vi/userinfo
