spring:
  config:
    activate:
      on-profile: local
---

spring:
  config:
    activate:
      on-profile: prod

  main:
    allow-bean-definition-overriding: true # for config error

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://simpletrip-db.cznmvedo4osi.ap-northeast-2.rds.amazonaws.com:3306/simpletrip
    username: admin
    password: simple123

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
        show_sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

logging:
  level:
    sql: info
