spring:
  main:
    allow-bean-definition-overriding: true # for config error

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: ${DDL_AUTO}
        show_sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB

logging:
  level:
    sql: info

app:
  # oauth setting
  google:
    api:
      url: https://oauth2.googleapis.com/tokeninfo

  # security setting
  security:
    credential: ${SECRET_CREDENTIAL}

# jwt settings
jwt:
  header: Authorization
  secret: ${JWT_SECRET}
  live:
    atk: 1800000 # 60 * 30 * 1000
    rtk: 2592000000 # 60 * 60 * 24 * 30 * 1000

# AWS S3 settings
cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET_NAME}
      url: ${S3_URL}
      tripGenieProfileUrl: ${GENIE_PROFILE_URL}
    region:
      static: ${S3_REGION}
    stack:
      auto: false